[package]
name = "mono-rs"
description = "Lightweight wrapper around mono."
authors = ["Bartosz 'b4rti' Gorol"]
repository = "https://github.com/b4rti/mono-rs"
license = "MIT"
version = "0.1.9"
edition = "2021"
links = "mono-2.0"

[dependencies]
