name: Rust

on:
  push:
    branches:
      - "master"
      - "feature/**"
  pull_request:
    branches:
      - "master"
      - "feature/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install earthly
      run: sudo apt update -y && sudo apt upgrade -y && sudo apt install -y eartly
    - name: Run build
      run: earthly --ci +all

